name: Build and install the package and then use it to update the online docs with github pages

on:
  workflow_dispatch:
  
  push:
    branches:    
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          sudo apt-get update && sudo apt-get install libboost-log-dev libboost-filesystem-dev libboost-thread-dev python3.8-dev
        
      - name: Build baggianalysis and install it through pip
        run: pip install .
        
      - name: Check import from the command line
        run: |
          mkdir test-folder && pushd test-folder
          python -c 'import baggianalysis'
          popd
    
      - name: Install the documentation's requirements
        run: pip install --upgrade sphinx sphinx_rtd_theme recommonmark
    
      - name: Build the docs
        run: |
          pushd docs
          make html
          popd
        
      # Publish built docs to gh-pages branch.
      # ===============================
      - name: Commit documentation changes
        run: |
          git clone https://github.com/lorenzo-rovigatti/baggianalysis.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "github-actions@github.com"
          git config --local user.name "CI workflow"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # ===============================
